Server:
  Mode: debug # server mode: release, debug, test
  BindAddress: :10001 # bind address
  ReadTimeout: 6
  WriteTimeout: 6

Oauth2:
  ClientID: 123245 # server mode: release, debug, test
  ClientSecret: dsa21321r2dadd.;d.d1[. # bind address
  Endpoint: 0.0.0.0:10001
  Scopes: All

Redis:
  Host: 127.0.0.1:6379
  Password: ""
  DB: 8


Mysql:
  DSN: root:admin123@tcp(127.0.0.1:3306)/oauth2?charset=utf8mb4&parseTime=true&loc=Local
  MaxIdleConnections: 100 # MySQL 最大空闲连接数，默认 100
  MaxOpenConnections: 100 # MySQL 最大打开的连接数，默认 100
  MaxConnectionLifeTime: 10s # 空闲连接最大存活时间，默认 10s

Log:
  Level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, panic, panic, fatal。
